In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('students.csv')

In [4]:
df

    Name   Age  Marks       City
0    Ali  20.0   85.0     Lahore
1   Sara  21.0   90.0    Karachi
2  Ahmad  19.0    NaN     Lahore
3  Aysha  20.0   88.0  Islamabad
4  Usman   NaN   70.0        NaN

In [5]:
df.shape

(5, 4)

In [6]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
 3   City    4 non-null      str
dtypes: float64(2), str(2)
memory usage: 292.0 bytes

In [8]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   20.000000  83.250000
std     0.816497   9.069179
min    19.000000  70.000000
25%    19.750000  81.250000
50%    20.000000  86.500000
75%    20.250000  88.500000
max    21.000000  90.000000

In [9]:
df.head()

    Name   Age  Marks       City
0    Ali  20.0   85.0     Lahore
1   Sara  21.0   90.0    Karachi
2  Ahmad  19.0    NaN     Lahore
3  Aysha  20.0   88.0  Islamabad
4  Usman   NaN   70.0        NaN

In [10]:
df[['Name', 'Age', 'City']]

    Name   Age       City
0    Ali  20.0     Lahore
1   Sara  21.0    Karachi
2  Ahmad  19.0     Lahore
3  Aysha  20.0  Islamabad
4  Usman   NaN        NaN

In [11]:
df.loc[0:0]

  Name   Age  Marks    City
0  Ali  20.0   85.0  Lahore

In [12]:
df[df['Marks'] < 80]

    Name  Age  Marks City
4  Usman  NaN   70.0  NaN

In [13]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     1
dtype: int64

In [14]:
df

    Name   Age  Marks       City
0    Ali  20.0   85.0     Lahore
1   Sara  21.0   90.0    Karachi
2  Ahmad  19.0    NaN     Lahore
3  Aysha  20.0   88.0  Islamabad
4  Usman   NaN   70.0        NaN

In [15]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [16]:
df

    Name   Age  Marks       City
0    Ali  20.0   85.0     Lahore
1   Sara  21.0   90.0    Karachi
2  Ahmad  19.0    NaN     Lahore
3  Aysha  20.0   88.0  Islamabad
4  Usman  20.0   70.0        NaN

In [17]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [18]:
df

    Name   Age  Marks       City
0    Ali  20.0  85.00     Lahore
1   Sara  21.0  90.00    Karachi
2  Ahmad  19.0  83.25     Lahore
3  Aysha  20.0  88.00  Islamabad
4  Usman  20.0  70.00        NaN

In [19]:
df["City"]=df["City"].fillna(df["City"].mode())

In [20]:
df

    Name   Age  Marks       City
0    Ali  20.0  85.00     Lahore
1   Sara  21.0  90.00    Karachi
2  Ahmad  19.0  83.25     Lahore
3  Aysha  20.0  88.00  Islamabad
4  Usman  20.0  70.00        NaN

In [21]:
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x > 70 else "Fail")

In [22]:
df

    Name   Age  Marks       City Result
0    Ali  20.0  85.00     Lahore   Pass
1   Sara  21.0  90.00    Karachi   Pass
2  Ahmad  19.0  83.25     Lahore   Pass
3  Aysha  20.0  88.00  Islamabad   Pass
4  Usman  20.0  70.00        NaN   Fail

In [23]:
df.head()

    Name   Age  Marks       City Result
0    Ali  20.0  85.00     Lahore   Pass
1   Sara  21.0  90.00    Karachi   Pass
2  Ahmad  19.0  83.25     Lahore   Pass
3  Aysha  20.0  88.00  Islamabad   Pass
4  Usman  20.0  70.00        NaN   Fail